### PR TITLE
feat: add dummy voting_power_validation_strategies_parsed_metadata

### PR DESCRIPTION
**Pull request by Sekhmet**
Not indexing anything there, just adding it to schema.

Compatibility with https://github.com/snapshot-labs/sx-api/pull/192

Will need to re-deploy it again, sorry 😢

### CODE REVIEW

**Comment by bonustrack** [comment]
All good will do that, the only problem is that it's slow to sync

**Comment by Sekhmet** [comment]
@bonustrack if we don't care about history on some chains we can move start index to earlier block to make it faster to sync.

**Comment by bonustrack** [comment]
Wouldnt it break with if there is proposal or vote on some space created before the start block?

**Comment by bonustrack** [comment]
I'm thinking also to seprate testnets and livenets in our interface with testnet.snapshotx.xyz and snapshotx.xyz

**Comment by Sekhmet** [comment]
> Wouldnt it break with if there is proposal or vote on some space created before the start block?

I'm not sure what you mean, spaces and proposals/votes created before the new start block just won't show up in the API/UI.

**Pull request merged**
